apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    apps: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - port : 80
          targetPort: 80
          nodePort: 8080